version: '3.8'

services:
  neo4j:
    image: neo4j:5.24
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_backup:/backup
      - ./dump_location:/flask.dump

  flask_app:
    build: .
    environment:
      - SECRET_KEY=Test
      - NEO4J_URI=bolt://neo4j:password@neo4j:7687
      - DEBUG=True
    ports:
      - "5000:5000"
    depends_on:
      - neo4j

volumes:
  neo4j_data:
  neo4j_backup: